version: '3.8'

services:
  bot:
    build: .
    container_name: construct3store-bot
    restart: always
    volumes:
      - construct3store-data:/app/data
    env_file:
      - .env

volumes:
  construct3store-data: