version: '3.8'

services:
  bot:
    build: .
    container_name: construct3store-bot
    restart: always
    volumes:
      - construct3store-data:/app/data
    env_file:
      - .env
    command: python3 bot.py
    resources:
      limits:
        memory: 400M
  
  webhook:
    build: .
    container_name: construct3store-webhook
    restart: always
    volumes:
      - construct3store-data:/app/data
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: python3 payment_webhook.py
    environment:
      - WEBHOOK_PORT=5000
    resources:
      limits:
        memory: 400M

volumes:
  construct3store-data: